name: Test & Push
on:
  push:
    branches:
      - develop
jobs:
  build-image:
    name: Build Docker image 🐋
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and tag Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: evaristor/recurrator:latest

  test-module:
    name: Run tests 🐍
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Check code formatting
      run: docker compose run --rm cli make check
    - name: Run tests with coverage
      run: docker compose run --rm cli make coverage
    - name: Run mutation tests
      run: docker compose run --rm cli make mutants
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        verbose: true

  tag-release:
    name: Tag and push Docker image with latest and four-digit tags 🏷️
    needs: test-module
    runs-on: ubuntu-latest
    steps:
    - name: Update latest git tag
      uses: rickstaa/action-create-tag@main
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Push Docker image
      run: docker push evaristor/recurrator:latest
    - name: Tag and push with four-digit tag
      run: |
        four_digit_tag=$(date +%y%V)
        docker tag evaristor/recurrator:latest evaristor/recurrator:${four_digit_tag}
        docker push evaristor/recurrator:latest
        docker push evaristor/recurrator:${four_digit_tag}
