name: CI/CD Pipeline
on:
  push:
    branches:
      - develop
jobs:
  build-image:
    name: Build, Test and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Check code formatting
      run: docker compose run --rm cli make check
    - name: Run tests with coverage
      run: docker compose run --rm cli make coverage
    - name: Run mutation tests
      run: docker compose run --rm cli make mutants
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        verbose: true
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Push Docker image
      run: docker push evaristor/recurrator:latest
    - name: Tag and push with four-digit tag
      run: |
        four_digit_tag=$(date +%y%V)
        docker tag evaristor/recurrator:latest evaristor/recurrator:${four_digit_tag}
        docker push evaristor/recurrator:latest
        docker push evaristor/recurrator:${four_digit_tag}
